# Generated by Django 4.2.29 on 2026-03-24 15:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_recorded_by_payment_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayorder',
            name='notes',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
